# Project: ErisLITE
# Module: log_viewer.py
# Author: Liam Piper-Brandon
# Version: 0.5
# License: MIT
# Created: 2025-06-01
# Last Updated: 2026-03-17
# Description:
#   This module provides functionality to view snapshot logs generated by ErisLITE. It allows users
#   to browse through available snapshot logs, select one, and view its contents in a formatted manner.

import os

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table
from rich.align import Align

from ui.utils import clear_screen, show_header, pause_return

LOG_DIR = "data/logs"
console = Console()

# Function to view snapshot logs
def view_snapshot_logs():
    clear_screen()
    show_header("SNAPSHOT LOG VIEWER")

    try:
        if not os.path.exists(LOG_DIR):
            console.print("[yellow]No logs directory found.[/]")
            pause_return()
            return

        files = [f for f in os.listdir(LOG_DIR) if f.endswith(".txt") and "snapshot" in f]
        files.sort(reverse=True)

        if not files:
            console.print("[yellow]No snapshot logs found.[/]")
            pause_return()
            return

        table = Table(title="Available Snapshots", show_lines=True)
        table.add_column("Index", style="cyan", no_wrap=True)
        table.add_column("Filename", style="white")

        for i, file in enumerate(files, 1):
            table.add_row(str(i), file)

        console.print(Align.center(table))

        choice = Prompt.ask(
            "\n[bold green]Select a log to view[/] (1-{}) or [b]Q[/b] to cancel".format(len(files)),
            default="1"
        )

        if choice.lower() == 'q':
            return

        try:
            index = int(choice) - 1
        except ValueError:
            console.print("[red]Invalid selection.[/]")
            pause_return()
            return

        if index < 0 or index >= len(files):
            console.print("[red]Invalid selection.[/]")
            pause_return()
            return

        selected_file = os.path.join(LOG_DIR, files[index])
        clear_screen()
        show_header("LOG FILE: " + files[index])

        with open(selected_file, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
            console.print(Panel.fit(content, title="Snapshot Contents", padding=(1, 4)))

    except Exception as e:
        console.print(f"[red]Error reading logs:[/] {e}")

    pause_return()