# Project: ErisLITE
# Module: manager.py
# Author: Liam Piper-Brandon
# Version: 1.4.0
# License: MIT
# Created: 2026-09-26
# Last Updated: 2026-09-26
# Description: Lifecycle and event management for Odyssey Lite.

from collections.abc import Iterable

from erislite.deception.odyssey.config import (
    ListenerConfig,
    get_default_listeners,
)
from erislite.deception.odyssey.events import OdysseyEvent
from erislite.deception.odyssey.listeners import CanaryListener
from erislite.deception.odyssey.storage import append_event


class OdysseyManager:
    """Manage Odyssey Lite canary listeners and observed events."""

    def __init__(
        self,
        configs: Iterable[ListenerConfig] | None = None,
        host: str = "0.0.0.0",
    ) -> None:
        if configs is None:
            configs = get_default_listeners()

        self.host = host
        self.configs = tuple(configs)

        self._events: list[OdysseyEvent] = []
        self._listeners: list[CanaryListener] = []

    @property
    def running(self) -> bool:
        """Return whether any Odyssey listener is currently running."""

        return any(listener.running for listener in self._listeners)

    @property
    def events(self) -> tuple[OdysseyEvent, ...]:
        """Return a read-only snapshot of observed Odyssey events."""

        return tuple(self._events)

    @property
    def listeners(self) -> tuple[CanaryListener, ...]:
        """Return the currently configured listener objects."""

        return tuple(self._listeners)

    def start(self) -> None:
        """Create and start enabled Odyssey listeners."""

        if self.running:
            return

        self._listeners = []

        try:
            for config in self.configs:
                if not config.enabled:
                    continue

                listener = CanaryListener(
                    config=config,
                    event_callback=self._record_event,
                    host=self.host,
                )

                listener.start()
                self._listeners.append(listener)

        except OSError:
            self.stop()
            self._listeners = []
            raise

    def stop(self) -> None:
        """Stop all Odyssey listeners."""

        for listener in self._listeners:
            listener.stop()

    def clear_events(self) -> None:
        """Clear all currently stored Odyssey events."""

        self._events.clear()

    def _record_event(self, event: OdysseyEvent) -> None:
        """Store and persist an event generated by an Odyssey listener."""

        self._events.append(event)

        try:
            append_event(event)
        except OSError:
            pass