# Project: ErisLITE
# Module: manager.py
# Author: Liam Piper-Brandon
# Version: 1.4.0
# License: MIT
# Created: 2026-09-26
# Last Updated: 2026-09-28
# Description: Lifecycle and event management for Odyssey Lite.

from __future__ import annotations

import atexit
import threading
from collections import deque
from collections.abc import Iterable

from erislite.deception.odyssey.config import (
    ListenerConfig,
    get_default_listeners,
)
from erislite.deception.odyssey.events import OdysseyEvent
from erislite.deception.odyssey.listeners import CanaryListener
from erislite.deception.odyssey.storage import append_event

MAX_IN_MEMORY_EVENTS = 1000
DUPLICATE_WINDOW_SECONDS = 5


class OdysseyManager:
    """Manage Odyssey Lite canary listeners and observed events."""

    def __init__(
        self,
        configs: Iterable[ListenerConfig] | None = None,
        host: str = "0.0.0.0",
    ) -> None:
        if configs is None:
            configs = get_default_listeners()

        self.host = host
        self.configs = tuple(configs)

        self._events: deque[OdysseyEvent] = deque(
            maxlen=MAX_IN_MEMORY_EVENTS
        )
        self._last_events: dict[
            tuple[str, int, str],
            OdysseyEvent,
        ] = {}
        self._suppressed_events = 0
        self._event_lock = threading.Lock()
        self._listeners: list[CanaryListener] = []
        self._failed_ports: list[int] = []

    @property
    def running(self) -> bool:
        """Return whether any Odyssey listener is currently running."""

        return any(listener.running for listener in self._listeners)

    @property
    def events(self) -> tuple[OdysseyEvent, ...]:
        """Return a read-only snapshot of observed Odyssey events."""

        return tuple(self._events)

    @property
    def suppressed_events(self) -> int:
        """Return the number of duplicate events suppressed this session."""

        return self._suppressed_events

    @property
    def listeners(self) -> tuple[CanaryListener, ...]:
        """Return the currently configured listener objects."""

        return tuple(self._listeners)

    @property
    def failed_ports(self) -> tuple[int, ...]:
        """Return ports that failed to start during the latest start attempt."""

        return tuple(self._failed_ports)
    
    def start(self) -> None:
        """Create and start enabled Odyssey listeners."""

        if self.running:
            return

        self._listeners = []
        self._failed_ports = []

        for config in self.configs:
            if not config.enabled:
                continue

            listener = CanaryListener(
                config=config,
                event_callback=self._record_event,
                host=self.host,
            )

            try:
                listener.start()
            except OSError:
                listener.stop()
                self._failed_ports.append(config.port)
                continue

            self._listeners.append(listener)

    def stop(self) -> None:
        """Stop all Odyssey listeners."""

        for listener in self._listeners:
            listener.stop()

    def clear_events(self) -> None:
        """Clear all currently stored Odyssey events."""

        with self._event_lock:
            self._events.clear()
            self._last_events.clear()
            self._suppressed_events = 0

    def _record_event(self, event: OdysseyEvent) -> None:
        """Store and persist an event generated by an Odyssey listener."""

        with self._event_lock:
            key = (
                event.source_ip,
                event.destination_port,
                event.service,
            )

            previous = self._last_events.get(key)

            if previous is not None:
                elapsed = (
                    event.timestamp - previous.timestamp
                ).total_seconds()

                if 0 <= elapsed <= DUPLICATE_WINDOW_SECONDS:
                    self._suppressed_events += 1
                    return

            self._last_events[key] = event
            self._events.append(event)

            try:
                append_event(event)
            except OSError:
                pass


_shared_manager: OdysseyManager | None = None
_shared_lock = threading.Lock()


def get_manager() -> OdysseyManager:
    """Return the process-wide Odyssey manager, creating it on first use.

    The menu is entered and left many times per session, but the listeners
    and their bound ports live for the whole process. A single shared manager
    keeps the menu in sync with what is actually running.
    """

    global _shared_manager

    with _shared_lock:
        if _shared_manager is None:
            _shared_manager = OdysseyManager()
            atexit.register(_shared_manager.stop)

        return _shared_manager


def active_canary_ports() -> frozenset[int]:
    """Return ports bound by running Odyssey listeners in this process.

    Does not create the shared manager if Odyssey was never opened.
    """

    manager = _shared_manager

    if manager is None:
        return frozenset()

    return frozenset(
        listener.config.port
        for listener in manager.listeners
        if listener.running
    )
